### PR TITLE
Implementation for the Caw Client

### PR DESCRIPTION
**Pull request by floan**
Hey William, this is my implementation for the client (+ 1 change in the faz layer to enable actual streaming). After this you there will probably be 1-2 more PR's to add the stream test and clean up some code. Thanks for being so helpful!

### CODE REVIEW

**Comment by floan** [comment]
Actually sorry, DO NOT REVIEW until after you have reviewed the caw_function_impl PR, otherwise you will be reviewing some things twice.

**Comment by wsuppiger** [comment]
All good, should I review it yet?

**Comment by floan** [comment]
@williamsuppiger  Yup, you can review this now, thanks!

**Review by wsuppiger — APPROVED** [review]
Looks good!

**Pull request merged**
