### PR TITLE
Caw stream test

### PR DESCRIPTION
**Pull request by floan**
Just added a test for stream. Its just one very simple test. I'm checking for multiple posts to one hashtag, and one post to multiple hashtags in the same test to reduce the overhead lines of creating a user and posting a caw. Let me know if you want me to separate them!

### CODE REVIEW

**Review by wsuppiger — APPROVED** [review]
Good to go!

**Comment by wsuppiger** [comment]
Actually, just make sure you change `secondCallbackFunc` to `second_callback_func` for style guide

https://google.github.io/styleguide/cppguide.html#Formatting_Lambda_Expressions

**Comment by floan** [comment]
Done!

**Review by wsuppiger — APPROVED** [review]
Great!

**Pull request merged**
